spring:
  jpa:
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
        show-sql: true
    hibernate.ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/learnproject
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
  graphql:
    graphiql.enabled: true
    graphiql.path: /graphiql


graphql.servlet.maxQueryDepth: 5


spring.jpa.open-in-view: false

com:
  pada:
    learnproject:
      example:
        change-example-enum:
#          every 5 minutes between 08:00 and 15:59, Monday - Friday
          cron-job: 0 */5 8-15 * * 1-5