spring:
  jpa:
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
        show-sql: true
    hibernate.ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/learnproject
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
  graphql:
    graphiql.enabled: true
    graphiql.path: /graphiql
  main:
    allow-bean-definition-overriding: true

graphql.servlet.maxQueryDepth: 5

grpc:
  client:
    grpc-client:
      address: 'static://127.0.0.1:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
  server:
    port: 9091

server:
  port: 8081

